version: 2.1

orbs:
  circleci-tools: geos-esm/circleci-tools@0.11.0

jobs:
  build:
    docker:
      - image: gmao/ubuntu20-geos-env:v6.2.8-intelmpi_2021.3.0-intel_2021.3.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_AUTH_TOKEN
      - image: gmao/geos-bcs:v10.19.4
    steps:
      - checkout
      - run: ls /

